project:
  type: website
  output-dir: ../chasewienk.github.io

website:
  description: "A blog built with Quarto"
  site-url: https://chasewienk.github.io # you must change this appropriately for RSS feeds to work properly
  title: "Chase Wienk's Sports Site"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css

editor: visual

execute:
  freeze: auto